- name: zookeeper useradd
  user: 
     name: zookeeper 
     password: "{{ zookeeper_password |password_hash('sha512') }}"
     update_password: always
- name: tar zookeeper
  unarchive:
    src: "{{ zookeeper_filename }}"
    dest: /opt/
    group: zookeeper 
    owner: zookeeper 
    keep_newer: yes
- name:  create softlink
  file: 
   src: /opt/{{ zookeeper_version }}
   path: /opt/zookeeper
   state: link
- name: copy env file
  copy: 
    src: java.env
    dest: /opt/zookeeper/conf/
    owner: zookeeper 
    group: zookeeper 
- name: init config
  template: 
    src: zoo.cfg.j2
    dest: /opt/zookeeper/conf/zoo.cfg
    owner: zookeeper 
    group: zookeeper 
- name: mkdir data
  file:
    path: /home/zookeeper/zdata
    state: directory 
    owner: zookeeper 
    group: zookeeper 
- name: get id
  shell: grep `hostname -I` /opt/zookeeper/conf/zoo.cfg  |awk -F '.' '{print$2}'|awk -F '=' '{print$1}' >/home/zookeeper/zdata/myid
- name: update file attr
  file:
    path: /home/zookeeper/zdata/myid
    owner: zookeeper 
    group: zookeeper 
- name: add path
  shell: | 
    grep ZOOKEEPER_HOME /etc/profile || echo  'export ZOOKEEPER_HOME=/opt/zookeeper' >> /etc/profile
    grep ZOOKEEPER_HOME/bin  /etc/profile || echo  'export PATH=$ZOOKEEPER_HOME/bin:$PATH' >>/etc/profile
- name: start zookeeper
  shell: su - zookeeper -c '/opt/zookeeper/bin/zkServer.sh start' 
- name: poweron start
  shell: grep zkServer.sh /etc/rc.local ||  echo "su - zookeeper -c '/opt/zookeeper/bin/zkServer.sh start'" >>/etc/rc.local 

  
