skip_zookeeper: false
kafka_password: "{{ lookup('password', '/root/.{{inventory_hostname}}/kafka/passwd chars=ascii_letters,digits,hexdigits,punctuation length=12') }}"
kafka_filename: kafka_2.12-2.3.1.tgz
kafka_version: kafka_2.12-2.3.1
